### ISSUE TITLE
14.0 deltatech_purchase_price, vendor contact

### ISSUE THREAD

**Issue by timnis** [dhongu/deltatech#1051]
Hello,

If I choose Vendor with contact like this
![image](https://github.com/dhongu/deltatech/assets/31338854/65f661a7-271b-4ba9-a067-7fccf92a57ae)

And when I receive goods. It updates Last Purchase Price but in Purchase tab where you have same Vendor without contact, it doesn't update purchase price nor add new one with contact?

**Comment by danila12** [comment]
Hello, 
Please check if you have configured correctly the system parameters:
- purchase.update_standard_price - If set to True, the product's standard_price will be overwritten
- purchase.update_product_price - if set to False, the product supplier's price will not be modified, if set to True, the
      product's supplier price will be allways overwritten
- purchase.add_supplier_to_product - if set to True, the supplier and the price will be automatically added to the
      supplier info of the product, if set to False, no modifications will be made in the supplier info of the product
- purchase.update_list_price - if set to True, the list price will be updated according to trade markup value.
      If set to False, the list price will not be updated
- sale.list_price_round - decimal number to which the list price is rounded

**Comment by timnis** [comment]
Hello,

Thanks for quick reply.

We have following settings. So it should update supplier price. Need to test more...

![image](https://github.com/dhongu/deltatech/assets/31338854/b876205f-6e7f-4163-b83e-b050aa2e96dd)

**Comment by timnis** [comment]
Ok, made quick test.

On product we have purchase price 85€
![image](https://github.com/dhongu/deltatech/assets/31338854/179602a2-266c-4146-913b-57bf8b4ecd53)

Then I made new purchase order where is Vendor with contact, receive goods and checked prices. Last purchase price is updated but vendor price hasn't.
![image](https://github.com/dhongu/deltatech/assets/31338854/689927ba-18fa-408b-84c6-f44f392e9187)
![image](https://github.com/dhongu/deltatech/assets/31338854/4957a530-a3c0-47cd-822b-39147bb7c46f)
![image](https://github.com/dhongu/deltatech/assets/31338854/5f5f9869-57a1-4b24-84da-0b635d06f430)



Then I tried without contact, otherwise same. Then it will update vendor price.
![image](https://github.com/dhongu/deltatech/assets/31338854/7b6a4b3c-bead-48e5-820f-436efd5bd18d)
![image](https://github.com/dhongu/deltatech/assets/31338854/a049a45c-85ea-4ac0-bfdb-1234dbde65a5)


So there is some problems if contact is used.

**Comment by danila12** [comment]
Yes, the module checks if supplier is exactly the same in product and in purchase order. If a sub-contact is used, it doesn't check.

**Comment by timnis** [comment]
Could it be modified that if sub-contact is used it still check and update suppliers purchase price?

**Comment by danila12** [comment]
Yes, we'll make the changes this week.

**Comment by timnis** [comment]
Thank you 👍

**Comment by timnis** [comment]
Hello, just checked commits and cannot find this one? I assume this is not done?

**Comment by danila12** [comment]
Hello,
It's not done yet, we had some issues with this modification on our implementations. 
Will it be ok if we check for the commercial_partner_id of the sub-contact? If the parent of your sub-contact is a company, that company will be searched in the suppliers and the price updated.

**Comment by timnis** [comment]
Hello,
that could be even better solution. Then there is only one line per supplier on suppliers list (like in reality too). 
Odoo handles purchase price from partner even sub-contact is used on purchase order.
👍

**Comment by danila12** [comment]
Hello, we made the update to check for the commercial_partner_id of the subcontact, please check if it's ok.
