### ISSUE TITLE
User Error on inventory module 

### ISSUE THREAD

**Issue by maisondelgusto** [dhongu/deltatech#1162]
module: deltatech_change_uom
version: 16.0

**Steps to reproduce**

- Basically after having changed some unit of measures on products when I go into inventory (Inventory Overview) and click on "Internal Transfer" I get the following error:

"The unit of measure kg defined on the order line doesn't belong to the same category as the unit of measure Unit(s) defined on the product. Please correct the unit of measure defined on the order line or on the product, they should belong to the same category."

**Current behavior**
see above

**Expected behavior**
usual

**Comment by danila12** [comment]
Hello, 
Yes, the module doesn't verify if the user has selected the correct uom's, just changes the uom. We suppose that the user selects the correct uom's.

**Comment by maisondelgusto** [comment]
HI,
Thanks for answering.
I've been digging a bit more and I think there is an issue when there is more than 1 warehouse.
The error I was getting is related to INTERNAL TRANSFER MOVES. It doesn't update the UOM in the internal moves.
Unfortunately, I'm not a developer and it's difficult for me to suggest a fix.
I changed back the UOM on the product moved internally between WH and now I don't get the error anymore.

I guess the point of this module is to force changing UOM belonging to different categories.
