### ISSUE TITLE
deltatech_product_do_merge v11 : not admin cannot merge product 

### ISSUE THREAD

**Issue by h3llopy** [dhongu/deltatech#213]
An Error is being raised

 "Only the destination contact may be linked to existing Journal Items. Please ask the Administrator if you need to merge several contacts linked to existing Journal Items."

**Comment by danila12** [comment]
You need to be admin to merge products that have entries in account move lines.
If you don't want to check this, please remove lines 298 - 301 in wizard/base_product_merge.py:
        if (
            SUPERUSER_ID != self.env.uid
            and "account.move.line" in self.env
            and self.env["account.move.line"]
            .sudo()
            .search([("product_id", "in", [product.id for product in src_products])])
        ):
            raise UserError(
                _(
                    "Only the destination contact may be linked to existing Journal Items. Please ask the Administrator if you need to merge several contacts linked to existing Journal Items."
                )
            )

**Comment by h3llopy** [comment]
Cool! Great Support, Thanks
