### ISSUE TITLE
	deltatech_invoice_delivery

### ISSUE THREAD

**Issue by anoureldin** [dhongu/deltatech#370]
hello 
when i confirm invoice i get 
Not all products are available.
i want to allow delivery with negative stock

**Comment by danila12** [comment]
Hello,
The button doesn't allow you to deliver if you don't have all the products in stock.
In that case we recommend to follow the regular steps (create and confirm the quotation, deliver the goods and create the invoice).
You can try (at your own risk) to comment/remove the lines:
                    if not all(move.state == "assigned" for move in picking.move_lines):
                        raise UserError(_("Not all products are available."))
in models/sale.py

Regards,

**Comment by anoureldin** [comment]
it's working 
thanks for fast reply 
regards
