### ISSUE TITLE
stock_backorder_confirmation_view.xml not included?

### ISSUE THREAD

**Issue by iblys** [dhongu/deltatech#77]
module: deltatech_stock_date
version: 12.0

**Steps to reproduce**
date change field not visible on back order confirmation window.

**Current behavior**
date change not affecting back order transfers.

stock_backorder_confirmation_view.xml is not in manifest. Is it on purpose?

**Expected behavior**
i included it in manifest and its ok now. thanks for this useful addon.

**Comment by danila12** [comment]
Thanks for your feedback. We modified the manifest accordingly.
Regards,
