### ISSUE TITLE
Odoo 16 deltatech_website_stock_availability

### ISSUE THREAD

**Issue by Hermut** [dhongu/deltatech#865]
Odoo default template and given error:

​ Error while loading deltatech_website_stock_availability.VariantMixin: ajax.loadXML is not a function TypeError: ajax.loadXML is not a function
onError @ web.assets_frontend_minimal.min.js:8

web.assets_frontend_minimal.min.js:8 Error while loading deltatech_website_stock_availability.VariantMixin: ajax.loadXML is not a function TypeError: ajax.loadXML is not a function
    at web.assets_frontend_lazy.min.js:9594:237
    at web.assets_frontend_minimal.min.js:9:63
    at new Promise (<anonymous>)
    at processJob (web.assets_frontend_minimal.min.js:9:9)
    at Object.processJobs (web.assets_frontend_minimal.min.js:17:1)
    at web.assets_frontend_minimal.min.js:10:110

Availbility information not show on product page.

**Comment by dhongu** [comment]
I will check what the problem is

**Comment by dhongu** [comment]
We made some changes, please check again.

**Comment by Hermut** [comment]
Thank you. It seems work now.
